CREATE TABLE Usuario(
Id_Usuario INT IDENTITY(1,1) PRIMARY KEY,
Nome VARCHAR(255) NOT NULL,
Telefone VARCHAR(255) NOT NULL,
Email VARCHAR (255) NOT NULL,
Senha VARCHAR(255) NOT NULL)

CREATE TABLE Espaco(
Id_Espaco INT IDENTITY(1,1) PRIMARY KEY,
Nome VARCHAR(255) NOT NULL,
Endereco VARCHAR(255) NOT NULL,
Capacidade INT NOT NULL,
Valor NUMERIC NOT NULL,
Caminho_Imagem VARCHAR(255) NOT NULL,
Id_Usuario INT,
Del_Espaco INT,
FOREIGN KEY (Id_Usuario) REFERENCES Usuario(Id_Usuario))

CREATE TABLE Reserva(
Id_Reserva INT IDENTITY(1,1) PRIMARY KEY,
Data_Reserva DATETIME NOT NULL,
Id_Espaco INT NOT NULL,
Id_Usuario INT,
Status INT NOT NULL,
FOREIGN KEY (Id_Espaco) REFERENCES Espaco(Id_Espaco),
FOREIGN KEY (Id_Usuario) REFERENCES Usuario(Id_Usuario))